sudo: false

language: node_js

node_js:
 - '8'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install yarn --global

install:
  - yarn install --frozen-lockfile --no-optional

script:
  - yarn run ci-commitlint
  - yarn run ci-lerna-publish
