sudo: false

language: node_js

node_js:
 - '8'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - git checkout master
  - git reset --hard $TRAVIS_COMMIT
  - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> .npmrc

install:
  - yarn install --frozen-lockfile --no-optional

script:
  - yarn run ci-commitlint
  - yarn run ci-lerna-publish
